/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.userInterface;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JPanel;
import neu.edu.csye6200.data.DataStore;
import neu.edu.csye6200.interfaces.StudentDataMangementFactory;
import neu.edu.csye6200.model.ClassRoom;
import neu.edu.csye6200.model.Student;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel; 
import org.jfree.chart.JFreeChart; 
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset; 
import org.jfree.data.category.DefaultCategoryDataset; 
import org.jfree.data.general.Dataset;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author sahilmattoo
 */
public class EnrollmentGraphJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EnrollmentGraphJPanel
     */
    //private JPanel userProcessContainerJPanel;
    public EnrollmentGraphJPanel() {
        //this.userProcessContainerJPanel=userProcessControllerJPanel;
        initComponents();
        createBarChart();
    }
    
    public void createBarChart(){
         JFreeChart barChart = ChartFactory.createBarChart(
         "Student enrollment in each class",           
         "Classes",            
         "Students",            
         createDataset(),          
         PlotOrientation.VERTICAL,           
         true, true, false);
        
        ChartPanel chartPanel = new ChartPanel( barChart );        
        chartPanel.setPreferredSize(new java.awt.Dimension( 560 , 367 ) );
        chartPanel.setDomainZoomable(true);

        JPanel jPanel4 = new JPanel();
        jPanel4.setLayout(new BorderLayout());
        jPanel4.add(chartPanel, BorderLayout.NORTH);

        JFrame frame = new JFrame();
        frame.add(jPanel4);
        frame.pack();
        frame.setVisible(true);
    }

     private CategoryDataset createDataset( ) {
      int[] studentCounter= new int[]{0,0,0,0,0,0};
      List<Student> students=  StudentDataMangementFactory.getFactoryInstance().getObject().getDataList();
          for(Student s: students){
              int age= s.getAge();
              if(age >= 6 && age <= 12){
                  studentCounter[0]=studentCounter[0]+1;
              }else if(age >= 13 && age <= 24){
                  studentCounter[1]=studentCounter[1]+1;
              }else if(age >= 25 && age <= 35){
                  studentCounter[2]=studentCounter[2]+1;
              }else if(age >= 36 && age <= 47){
                  studentCounter[3]=studentCounter[3]+1;
              }else if(age >= 48 && age <= 59){
                  studentCounter[4]=studentCounter[4]+1;
              }else{
                  studentCounter[5]=studentCounter[5]+1;
              }     
      }       
      final DefaultCategoryDataset dataset = 
      new DefaultCategoryDataset( );  

      dataset.addValue( studentCounter[0], "Classroom-1", "Classroom-1" );        
      dataset.addValue( studentCounter[1], "Classroom-2", "Classroom-2" );       
      dataset.addValue( studentCounter[2], "Classroom-3", "Classroom-3" );      
      dataset.addValue( studentCounter[3], "Classroom-4", "Classroom-5" );        
      dataset.addValue( studentCounter[4], "Classroom-5", "Classroom-5" );
      dataset.addValue( studentCounter[5], "Classroom-6", "Classroom-6" );                

      return dataset; 
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
