/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.userInterface;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author raghavkhanna
 */
public class RenewalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RenewalJPanel
     */
    public RenewalJPanel() {
        initComponents();
    }

    public JButton getBtnRenew() {
        return btnRenew;
    }

    public void setBtnRenew(JButton btnRenew) {
        this.btnRenew = btnRenew;
    }

    public JTable getTblRenewalRecords() {
        return tblRenewalRecords;
    }

    public void setTblRenewalRecords(JTable tblRenewalRecords) {
        this.tblRenewalRecords = tblRenewalRecords;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRenewal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRenewalRecords = new javax.swing.JTable();
        btnRenew = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        lblRenewal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblRenewal.setForeground(new java.awt.Color(0, 0, 153));
        lblRenewal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRenewal.setText("Renewal For Students");
        add(lblRenewal);
        lblRenewal.setBounds(100, 40, 577, 30);

        tblRenewalRecords.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblRenewalRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fiirst Name", "Last Name", "Last Renewal", "Age", "Id"
            }
        ));
        jScrollPane1.setViewportView(tblRenewalRecords);

        add(jScrollPane1);
        jScrollPane1.setBounds(36, 90, 690, 226);

        btnRenew.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btnRenew.setText("Renew");
        add(btnRenew);
        btnRenew.setBounds(250, 350, 268, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/immu.jpeg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 900, 630);
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRenew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRenewal;
    private javax.swing.JTable tblRenewalRecords;
    // End of variables declaration//GEN-END:variables
}
