/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.userInterface;

import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author moinu
 */
public class RenewalJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RenewalJPanel
     */
    public RenewalJPanel() {
        initComponents();
    }

    public JButton getBtnRenew() {
        return btnRenew;
    }

    public void setBtnRenew(JButton btnRenew) {
        this.btnRenew = btnRenew;
    }

    public JTable getTblRenewalRecords() {
        return tblRenewalRecords;
    }

    public void setTblRenewalRecords(JTable tblRenewalRecords) {
        this.tblRenewalRecords = tblRenewalRecords;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRenewal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRenewalRecords = new javax.swing.JTable();
        btnRenew = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblRenewal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRenewal.setForeground(new java.awt.Color(0, 0, 153));
        lblRenewal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRenewal.setText("Renewal For Students");

        tblRenewalRecords.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblRenewalRecords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fiirst Name", "Last Name", "Last Renewal", "Age", "Id"
            }
        ));
        jScrollPane1.setViewportView(tblRenewalRecords);

        btnRenew.setText("Renew");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(lblRenewal, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRenew, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblRenewal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRenew, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRenew;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblRenewal;
    private javax.swing.JTable tblRenewalRecords;
    // End of variables declaration//GEN-END:variables
}
